#!/bin/bash

set -e

mysql --protocol=socket -uroot -p$MYSQL_ROOT_PASSWORD <<EOSQL
CREATE DATABASE moviecatalog;

CREATE USER '$MOVIE_CATALOG_DB_USER'@'%' identified by '$MOVIE_CATALOG_DB_PASSWORD';
SHOW GRANTS FOR '$MOVIE_CATALOG_DB_USER'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON moviecatalog.* TO '$MOVIE_CATALOG_DB_USER'@'%';

create user '$MOVIE_CATALOG_DB_LB_USER'@'%' identified by '$MOVIE_CATALOG_DB_LB_PASSWORD';
SHOW GRANTS FOR '$MOVIE_CATALOG_DB_LB_USER'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, TRIGGER ON moviecatalog.* TO '$MOVIE_CATALOG_DB_LB_USER'@'%';

flush privileges;

EOSQL